### PR TITLE
Fix Linux setup tutorial

### PR DESCRIPTION
**Pull request by naknut**
It seems like the setup instructions in this part was just copy/pasted from the macOS setup. According to the documentation [found here](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/tools/idf-docker-image.html#using-remote-serial-port) the device usually shows up as `/dev/ttyUSB0` on Linux, and that was true for me as well.

### CODE REVIEW

**Comment by rauhul** [comment]
Thanks for the PR, I think the wording in this tutorial is correct because it's referring to running a Linux docker container on a macOS Host machine. Do you have a suggestion for alternative wording for both macOS _and_ Linux host machines?

**Comment by naknut** [comment]
The tutorial is split in "Get started on macOS" which sets you up on macOS not using Docker or "Get started on Linux using Docker" (see the screenshot). If the tutorial is supposed to be for both macOS and Linux its not obvious at all since macOS is not mentioned. I guess it could work on mac as well, but I feel like the whole tutorial needs to be rewritten if so.

image

**Comment by rauhul** [comment]
I mean that's kind of the point. The host OS doesn't really matter, this tutorial should generally work with a windows host as well. 

If you have suggestions on how to reword the content to make this tutorial more clear, I'd be happy to review it.

**Comment by naknut** [comment]
@rauhul the documentation has been updated and reworded to better reflect that its for any platform with Docker.

**Comment by naknut** [comment]
@rauhul did you get the chance to look at my latest changes?

**Comment by rauhul** [comment]
Sorry I had forgotten about this pr, I think I would still like to include Linux because it is the guest OS somewhere in the article title. Any ideas?

**Comment by naknut** [comment]
> Sorry I had forgotten about this pr, I think I would still like to include Linux because it is the guest OS somewhere in the article title. Any ideas?

@rauhul : Should we call it "Get started on Linux or macOS using Docker"? Or would that be confusing since there will be two tutorials on how to get started on macOS?

**Comment by rauhul** [comment]
> @rauhul : Should we call it "Get started on Linux or macOS using Docker"? Or would that be confusing since there will be two tutorials on how to get started on macOS?

I think mentioning additional host operating systems like macOS is not desirable because this guide should generally also work on windows/wsl.

Maybe "Get started on a Linux Docker container", I don't love that title but it's more clear.

**Comment by naknut** [comment]
> > @rauhul : Should we call it "Get started on Linux or macOS using Docker"? Or would that be confusing since there will be two tutorials on how to get started on macOS?
> 
> I think mentioning additional host operating systems like macOS is not desirable because this guide should generally also work on windows/wsl.
> 
> Maybe "Get started on a Linux Docker container", I don't love that title but it's more clear.

Ok! I have updated the wording to reflect your suggestion.

**Review by rauhul — APPROVED** [review]
Looks good to go, thanks for working through the feedback and contributing!

**Comment by rauhul** [comment]
Updated documentation should now be live

**Pull request merged**
