### PR TITLE
Update the ESP-IDF tooling to master (or v5.4 when released) to fix Embedded Swift Crashes

### PR DESCRIPTION
**Pull request by PaulSolt**
Fixes Embedded Swift issues. Random numbers do not work on 5.1.2 - 5.3.1 in addition to several issues.

Note: The fix is on master, but we don't have a 5.4 release yet. Since Embedded Swift is experimental, it makes sense to be recommending tooling that solves current problems. There is some risk in not having a stable ESP-IDF release.

> Please stay in the master (v5.4) branch. Don't checkout to the release v5.2 or v5.3
> As a summary;
> We have fixed the The gap between ...  errors in this repo with the 2eb2975 . No change in the IDF releases.
> We don't have getentropy error in IDF master (v5.4) branch. No need to apply a patch.
> For the previous idf releases (v5.3.x and v5.2.x), apply the patch I prepared. https://github.com/user-attachments/files/15877608/0001-newlib-getentropy-implementation.patch

https://github.com/apple/swift-embedded-examples/issues/17#issuecomment-2348454444

### CODE REVIEW

**Comment by rauhul** [comment]
I'd like to hold off on this until 5.4 is released

**Comment by rauhul** [comment]
@erhankur do we have a rough idea of when 5.4.0 will be released?

**Comment by erhankur** [comment]
@rauhul We plan to make the final release in February next year.

**Comment by rauhul** [comment]
Oh ok thats a while away, we can use the `master` branch until then.

**Review by rauhul — APPROVED** [review]

**Pull request merged**
